# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oraclelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=50)),
                ('tnsname', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('charset', models.CharField(max_length=100)),
                ('ncharset', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('alertpath', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=300)),
                ('monitor_type', models.IntegerField(default=1)),
                ('performance_type', models.IntegerField(default=0)),
                ('hit_type', models.IntegerField(default=1)),
            ],
        ),
    ]
