# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oraclelist',
            name='hit_type',
        ),
    ]
