# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_oraclelist_hit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraclelist',
            name='hit_type',
            field=models.IntegerField(default=1),
        ),
    ]
