# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_oraclelist_hit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='oraclestatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnsname', models.CharField(max_length=100)),
                ('ipaddress', models.GenericIPAddressField()),
                ('dbsize', models.CharField(max_length=50)),
                ('tbstatus', models.CharField(max_length=200)),
                ('host_name', models.CharField(default='host', max_length=50)),
                ('version', models.CharField(default='10', max_length=50)),
                ('startup_time', models.CharField(default='2015', max_length=50)),
                ('archiver', models.CharField(default='opened', max_length=20)),
                ('sga_size', models.IntegerField(default=0)),
            ],
        ),
    ]
